# Generated by Django 4.1.4 on 2023-05-08 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoapp', '0002_booktable_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=700)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 23, 17, 37, 167187)),
        ),
    ]
